name: Releases
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "LICENSE,exporter.py,extension.yaml,README.md"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}